// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIwydwDY50BycOJAwEKeh_Orkc1LwUyg0',
    appId: '1:994766503452:web:3ebfce8cac1e509dba29d9',
    messagingSenderId: '994766503452',
    projectId: 'i-chat-880b4',
    authDomain: 'i-chat-880b4.firebaseapp.com',
    storageBucket: 'i-chat-880b4.appspot.com',
    measurementId: 'G-RXVGFNHQDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAViCS3f53Uagf3MoY8lA_ZI8HHGrlDBP4',
    appId: '1:994766503452:android:c2fe178d0e5dad7aba29d9',
    messagingSenderId: '994766503452',
    projectId: 'i-chat-880b4',
    storageBucket: 'i-chat-880b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6UquDVStNgyM7fuI-jRfn7Zh79DtsxvY',
    appId: '1:994766503452:ios:b69e3872b4ef6863ba29d9',
    messagingSenderId: '994766503452',
    projectId: 'i-chat-880b4',
    storageBucket: 'i-chat-880b4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6UquDVStNgyM7fuI-jRfn7Zh79DtsxvY',
    appId: '1:994766503452:ios:b69e3872b4ef6863ba29d9',
    messagingSenderId: '994766503452',
    projectId: 'i-chat-880b4',
    storageBucket: 'i-chat-880b4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIwydwDY50BycOJAwEKeh_Orkc1LwUyg0',
    appId: '1:994766503452:web:3246c7bb7c28ae41ba29d9',
    messagingSenderId: '994766503452',
    projectId: 'i-chat-880b4',
    authDomain: 'i-chat-880b4.firebaseapp.com',
    storageBucket: 'i-chat-880b4.appspot.com',
    measurementId: 'G-VWVPJCLNLH',
  );
}
